

USE squirdb;

-- 12. COUNTRIES — lookup table (ISO 3166-1 alpha-2 code + name)
CREATE TABLE IF NOT EXISTS countries (
    country_code CHAR(2)     NOT NULL PRIMARY KEY,
    country_name VARCHAR(80) NOT NULL,

    CONSTRAINT uq_countries_name UNIQUE (country_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



-- 13. CITIES — catalog of cities the user can add as a World Clock.
--     The country name lives in COUNTRIES (3NF); the time zone is the
--     IANA identifier that the browser uses to compute the local time.
CREATE TABLE IF NOT EXISTS cities (
    city_id      INT AUTO_INCREMENT PRIMARY KEY,
    country_code CHAR(2)     NOT NULL,
    city_name    VARCHAR(80) NOT NULL,
    timezone     VARCHAR(64) NOT NULL,   -- e.g. Asia/Manila

    CONSTRAINT fk_cities_country
        FOREIGN KEY (country_code) REFERENCES countries(country_code)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT uq_cities_country_name UNIQUE (country_code, city_name),
    INDEX idx_cities_name (city_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



-- 14. USER_WORLD_CLOCKS — bridge/associative entity (users M:N cities).
--     The "Local" clock is not stored: it always follows the device time zone.
CREATE TABLE IF NOT EXISTS user_world_clocks (
    user_id    INT NOT NULL,
    city_id    INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (user_id, city_id),

    CONSTRAINT fk_world_clocks_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_world_clocks_city
        FOREIGN KEY (city_id) REFERENCES cities(city_id)
        ON DELETE CASCADE,

    INDEX idx_world_clocks_city (city_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



-- Seed data for the World Clock city picker
INSERT IGNORE INTO countries (country_code, country_name) VALUES
    ('AF', 'Afghanistan'),
    ('DZ', 'Algeria'),
    ('AR', 'Argentina'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('BD', 'Bangladesh'),
    ('BE', 'Belgium'),
    ('BO', 'Bolivia'),
    ('BR', 'Brazil'),
    ('KH', 'Cambodia'),
    ('CA', 'Canada'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CO', 'Colombia'),
    ('CU', 'Cuba'),
    ('CZ', 'Czech Republic'),
    ('DK', 'Denmark'),
    ('EC', 'Ecuador'),
    ('EG', 'Egypt'),
    ('ET', 'Ethiopia'),
    ('FJ', 'Fiji'),
    ('FI', 'Finland'),
    ('FR', 'France'),
    ('DE', 'Germany'),
    ('GH', 'Ghana'),
    ('GR', 'Greece'),
    ('GU', 'Guam'),
    ('HK', 'Hong Kong'),
    ('HU', 'Hungary'),
    ('IS', 'Iceland'),
    ('IN', 'India'),
    ('ID', 'Indonesia'),
    ('IR', 'Iran'),
    ('IQ', 'Iraq'),
    ('IE', 'Ireland'),
    ('IL', 'Israel'),
    ('IT', 'Italy'),
    ('JM', 'Jamaica'),
    ('JP', 'Japan'),
    ('KE', 'Kenya'),
    ('KW', 'Kuwait'),
    ('LA', 'Laos'),
    ('MY', 'Malaysia'),
    ('MX', 'Mexico'),
    ('MN', 'Mongolia'),
    ('MA', 'Morocco'),
    ('MM', 'Myanmar'),
    ('NP', 'Nepal'),
    ('NL', 'Netherlands'),
    ('NZ', 'New Zealand'),
    ('NG', 'Nigeria'),
    ('NO', 'Norway'),
    ('PK', 'Pakistan'),
    ('PA', 'Panama'),
    ('PG', 'Papua New Guinea'),
    ('PE', 'Peru'),
    ('PH', 'Philippines'),
    ('PL', 'Poland'),
    ('PT', 'Portugal'),
    ('PR', 'Puerto Rico'),
    ('QA', 'Qatar'),
    ('RO', 'Romania'),
    ('RU', 'Russia'),
    ('SA', 'Saudi Arabia'),
    ('SG', 'Singapore'),
    ('ZA', 'South Africa'),
    ('KR', 'South Korea'),
    ('ES', 'Spain'),
    ('LK', 'Sri Lanka'),
    ('SE', 'Sweden'),
    ('CH', 'Switzerland'),
    ('TW', 'Taiwan'),
    ('TZ', 'Tanzania'),
    ('TH', 'Thailand'),
    ('TN', 'Tunisia'),
    ('TR', 'Turkey'),
    ('UA', 'Ukraine'),
    ('AE', 'United Arab Emirates'),
    ('GB', 'United Kingdom'),
    ('US', 'United States'),
    ('UY', 'Uruguay'),
    ('UZ', 'Uzbekistan'),
    ('VE', 'Venezuela'),
    ('VN', 'Vietnam');

INSERT IGNORE INTO cities (country_code, city_name, timezone) VALUES
    ('AE', 'Abu Dhabi', 'Asia/Dubai'),
    ('GH', 'Accra', 'Africa/Accra'),
    ('ET', 'Addis Ababa', 'Africa/Addis_Ababa'),
    ('AU', 'Adelaide', 'Australia/Adelaide'),
    ('DZ', 'Algiers', 'Africa/Algiers'),
    ('NL', 'Amsterdam', 'Europe/Amsterdam'),
    ('US', 'Anchorage', 'America/Anchorage'),
    ('GR', 'Athens', 'Europe/Athens'),
    ('NZ', 'Auckland', 'Pacific/Auckland'),
    ('IQ', 'Baghdad', 'Asia/Baghdad'),
    ('TH', 'Bangkok', 'Asia/Bangkok'),
    ('ES', 'Barcelona', 'Europe/Madrid'),
    ('CN', 'Beijing', 'Asia/Shanghai'),
    ('DE', 'Berlin', 'Europe/Berlin'),
    ('CO', 'Bogota', 'America/Bogota'),
    ('AU', 'Brisbane', 'Australia/Brisbane'),
    ('BE', 'Brussels', 'Europe/Brussels'),
    ('RO', 'Bucharest', 'Europe/Bucharest'),
    ('HU', 'Budapest', 'Europe/Budapest'),
    ('AR', 'Buenos Aires', 'America/Argentina/Buenos_Aires'),
    ('EG', 'Cairo', 'Africa/Cairo'),
    ('AU', 'Canberra', 'Australia/Sydney'),
    ('ZA', 'Cape Town', 'Africa/Johannesburg'),
    ('VE', 'Caracas', 'America/Caracas'),
    ('MA', 'Casablanca', 'Africa/Casablanca'),
    ('US', 'Chicago', 'America/Chicago'),
    ('LK', 'Colombo', 'Asia/Colombo'),
    ('DK', 'Copenhagen', 'Europe/Copenhagen'),
    ('TZ', 'Dar es Salaam', 'Africa/Dar_es_Salaam'),
    ('AU', 'Darwin', 'Australia/Darwin'),
    ('US', 'Denver', 'America/Denver'),
    ('BD', 'Dhaka', 'Asia/Dhaka'),
    ('QA', 'Doha', 'Asia/Qatar'),
    ('AE', 'Dubai', 'Asia/Dubai'),
    ('IE', 'Dublin', 'Europe/Dublin'),
    ('GB', 'Edinburgh', 'Europe/London'),
    ('DE', 'Frankfurt', 'Europe/Berlin'),
    ('CH', 'Geneva', 'Europe/Zurich'),
    ('GU', 'Hagatna', 'Pacific/Guam'),
    ('CA', 'Halifax', 'America/Halifax'),
    ('VN', 'Hanoi', 'Asia/Ho_Chi_Minh'),
    ('CU', 'Havana', 'America/Havana'),
    ('FI', 'Helsinki', 'Europe/Helsinki'),
    ('VN', 'Ho Chi Minh City', 'Asia/Ho_Chi_Minh'),
    ('HK', 'Hong Kong', 'Asia/Hong_Kong'),
    ('US', 'Honolulu', 'Pacific/Honolulu'),
    ('TR', 'Istanbul', 'Europe/Istanbul'),
    ('ID', 'Jakarta', 'Asia/Jakarta'),
    ('IL', 'Jerusalem', 'Asia/Jerusalem'),
    ('ZA', 'Johannesburg', 'Africa/Johannesburg'),
    ('AF', 'Kabul', 'Asia/Kabul'),
    ('PK', 'Karachi', 'Asia/Karachi'),
    ('NP', 'Kathmandu', 'Asia/Kathmandu'),
    ('JM', 'Kingston', 'America/Jamaica'),
    ('IN', 'Kolkata', 'Asia/Kolkata'),
    ('MY', 'Kuala Lumpur', 'Asia/Kuala_Lumpur'),
    ('KW', 'Kuwait City', 'Asia/Kuwait'),
    ('UA', 'Kyiv', 'Europe/Kiev'),
    ('BO', 'La Paz', 'America/La_Paz'),
    ('NG', 'Lagos', 'Africa/Lagos'),
    ('PE', 'Lima', 'America/Lima'),
    ('PT', 'Lisbon', 'Europe/Lisbon'),
    ('GB', 'London', 'Europe/London'),
    ('US', 'Los Angeles', 'America/Los_Angeles'),
    ('ES', 'Madrid', 'Europe/Madrid'),
    ('GB', 'Manchester', 'Europe/London'),
    ('PH', 'Manila', 'Asia/Manila'),
    ('AU', 'Melbourne', 'Australia/Melbourne'),
    ('MX', 'Mexico City', 'America/Mexico_City'),
    ('IT', 'Milan', 'Europe/Rome'),
    ('UY', 'Montevideo', 'America/Montevideo'),
    ('RU', 'Moscow', 'Europe/Moscow'),
    ('IN', 'Mumbai', 'Asia/Kolkata'),
    ('KE', 'Nairobi', 'Africa/Nairobi'),
    ('IN', 'New Delhi', 'Asia/Kolkata'),
    ('US', 'New York', 'America/New_York'),
    ('JP', 'Osaka', 'Asia/Tokyo'),
    ('NO', 'Oslo', 'Europe/Oslo'),
    ('PA', 'Panama City', 'America/Panama'),
    ('FR', 'Paris', 'Europe/Paris'),
    ('AU', 'Perth', 'Australia/Perth'),
    ('KH', 'Phnom Penh', 'Asia/Phnom_Penh'),
    ('US', 'Phoenix', 'America/Phoenix'),
    ('PG', 'Port Moresby', 'Pacific/Port_Moresby'),
    ('CZ', 'Prague', 'Europe/Prague'),
    ('EC', 'Quito', 'America/Guayaquil'),
    ('IS', 'Reykjavik', 'Atlantic/Reykjavik'),
    ('SA', 'Riyadh', 'Asia/Riyadh'),
    ('IT', 'Rome', 'Europe/Rome'),
    ('US', 'San Francisco', 'America/Los_Angeles'),
    ('PR', 'San Juan', 'America/Puerto_Rico'),
    ('CL', 'Santiago', 'America/Santiago'),
    ('BR', 'Sao Paulo', 'America/Sao_Paulo'),
    ('KR', 'Seoul', 'Asia/Seoul'),
    ('CN', 'Shanghai', 'Asia/Shanghai'),
    ('SG', 'Singapore', 'Asia/Singapore'),
    ('SE', 'Stockholm', 'Europe/Stockholm'),
    ('FJ', 'Suva', 'Pacific/Fiji'),
    ('AU', 'Sydney', 'Australia/Sydney'),
    ('TW', 'Taipei', 'Asia/Taipei'),
    ('UZ', 'Tashkent', 'Asia/Tashkent'),
    ('IR', 'Tehran', 'Asia/Tehran'),
    ('JP', 'Tokyo', 'Asia/Tokyo'),
    ('CA', 'Toronto', 'America/Toronto'),
    ('TN', 'Tunis', 'Africa/Tunis'),
    ('MN', 'Ulaanbaatar', 'Asia/Ulaanbaatar'),
    ('CA', 'Vancouver', 'America/Vancouver'),
    ('AT', 'Vienna', 'Europe/Vienna'),
    ('LA', 'Vientiane', 'Asia/Vientiane'),
    ('PL', 'Warsaw', 'Europe/Warsaw'),
    ('US', 'Washington DC', 'America/New_York'),
    ('NZ', 'Wellington', 'Pacific/Auckland'),
    ('MM', 'Yangon', 'Asia/Yangon'),
    ('CH', 'Zurich', 'Europe/Zurich');

